### ISSUE TITLE
AISViz Website

### ISSUE THREAD

**Issue by gabrielspadon** [AISViz/.github#2]
Create a website for the project using https://pages.github.com/ and host it on a Dalhousie domain for future reference. Include in this website information about the team, the grant, and templates for contacting us and increasing our outreach.

**Comment by Jinnkunn** [comment]
Could we finalize the domain we wish to use? Would **aisviz.cs.dal.ca** be suitable? @gabrielspadon @JayKumarr 

I can reach out to the IT department to inquire about establishing a CNAME connection to GitHub first.

**Comment by Jinnkunn** [comment]
The initialization of GitHub Pages is complete. You can view it at: https://aisviz.github.io/

**Comment by Jinnkunn** [comment]
Hi @gabrielspadon , I have experience with WordPress for web development. However, our current project leverages GitHub Pages, which requires the use of a static site generator. I do have some little experience in this area, primarily with utilizing templates for themes and populating them with content, no experience with writing themes from 0.

**Comment by 0leks11** [comment]
Dear Gabriel Spadon and Team,

My name is Oleksii. I worked as an engineer on merchant vessels for 10 years, and while I have since changed my profession, my engineering approach to work remains unchanged. I am currently building my first website, which serves as my online resume. One section of this website highlights my experience as a marine engineer, as well as my skills as an IT specialist. In this section, I aim to display data about the 11 vessels I have worked on, utilizing WebSocket technology.

At the moment, I am using AIS Stream (http://aisstream.io) to display vessel data. However, there is a challenge: the vessels I worked on primarily make transoceanic voyages. They spend only 1-3 days in port, with the rest of the time far away from shore stations. During these periods, I cannot receive any data via WebSocket because AIS Stream only provides information from coastal stations.

This is why I am reaching out to you, Gabriel, and your team. I would like to use AISDB MERIDIAN technology to display data for the 11 vessels that are a significant part of my professional history. I am not conducting business, researching environmental topics, or pursuing commercial goals. This website is a personal project that serves as a demonstration of my capabilities as an IT specialist and showcases my experience in the maritime industry. I assure you that access to the technology will remain solely with me and will be used exclusively for this project.

It would mean a lot to me if you could grant me access to WebSocket and AISDB MERIDIAN. I deeply respect your work and understand the value of your technology, and I promise to use it solely for the stated purposes.

Additionally, I want to clarify that I am not a student of any Canadian university.

I would sincerely appreciate any opportunity for collaboration.

Best regards,
Oleksii Kozyrev
GitHub: 0leks11
LinkedIn: www.linkedin.com/in/oleksii-kozyrev-106b37261
Email: ak.kozyrev01@gmail.com
